CREATE TABLE IF NOT EXISTS "DisasterAlert" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"eventId" varchar(50) NOT NULL,
	"eventType" varchar(10) NOT NULL,
	"alertLevel" varchar(20) NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"country" varchar(100),
	"latitude" numeric(10, 6),
	"longitude" numeric(10, 6),
	"minLatitude" numeric(10, 6),
	"maxLatitude" numeric(10, 6),
	"minLongitude" numeric(10, 6),
	"maxLongitude" numeric(10, 6),
	"magnitude" numeric(5, 2),
	"depth" numeric(8, 3),
	"affectedPopulation" integer,
	"affectedArea" integer,
	"deaths" integer,
	"displaced" integer,
	"eventTime" timestamp,
	"startTime" timestamp,
	"endTime" timestamp,
	"publishedAt" timestamp NOT NULL,
	"lastUpdated" timestamp NOT NULL,
	"reportUrl" text,
	"capUrl" text,
	"iconUrl" text,
	"severity" integer,
	"version" integer,
	"isActive" boolean DEFAULT true NOT NULL,
	"rawData" json,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "DisasterAlert_eventId_unique" UNIQUE("eventId")
);
