#!/usr/bin/env tsx

import { config } from 'dotenv';
import { drizzle } from 'drizzle-orm/neon-http';
import { neon } from '@neondatabase/serverless';
import {
  productCategory,
  product,
  regionalProductPreference,
  productInventory,
} from '../lib/db/schema';
import { eq } from 'drizzle-orm';

// Sample Product Categories
const sampleProductCategories = [
  {
    name: 'Blankets & Bedding',
    description: 'Blankets, sleeping bags, and bedding materials',
    icon: 'blanket',
    color: '#4A90E2',
  },
  {
    name: 'Winterization Kits',
    description: 'Complete winter clothing and gear kits',
    icon: 'winter',
    color: '#7ED321',
  },
  {
    name: 'Kitchen Sets',
    description: 'Cooking utensils and kitchen equipment',
    icon: 'kitchen',
    color: '#F5A623',
  },
  {
    name: 'First Aid',
    description: 'Medical supplies and first aid kits',
    icon: 'first-aid',
    color: '#D0021B',
  },
  {
    name: 'Water & Sanitation',
    description: 'Water containers, filters, and purification',
    icon: 'water',
    color: '#50E3C2',
  },
  {
    name: 'Ready-to-Eat Food',
    description: 'Non-perishable food items',
    icon: 'food',
    color: '#9013FE',
  },
  {
    name: 'Shelter & Tents',
    description: 'Tents, tarpaulins, and shelter materials',
    icon: 'tent',
    color: '#8B572A',
  },
];

// Sample Products - Blankets
const sampleBlanketProducts = [
  {
    name: 'Blanket (Polyester)',
    description: 'Warm polyester blanket for emergency situations',
    specification: '210*220 cm, 3.5kg minimum weight',
    quantity: 1,
    unit: 'piece',
    size: '210*220',
    weight: '3.5',
    dimensions: '210*220 cm',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/blanket-polyester.jpg',
    itemCode: 'BLK-001',
    categoryId: 'blankets-bedding',
  },
  {
    name: 'Wool Blanket (Heavy)',
    description: 'Heavy wool blanket for extreme cold conditions',
    specification: '200*180 cm, 2.8kg, 100% wool',
    quantity: 1,
    unit: 'piece',
    size: '200*180',
    weight: '2.8',
    dimensions: '200*180 cm',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/wool-blanket.jpg',
    itemCode: 'BLK-002',
    categoryId: 'blankets-bedding',
  },
  {
    name: 'Fleece Blanket (Light)',
    description: 'Lightweight fleece blanket for moderate temperatures',
    specification: '180*150 cm, 0.8kg, polyester fleece',
    quantity: 1,
    unit: 'piece',
    size: '180*150',
    weight: '0.8',
    dimensions: '180*150 cm',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/fleece-blanket.jpg',
    itemCode: 'BLK-003',
    categoryId: 'blankets-bedding',
  },
  {
    name: 'Emergency Thermal Blanket',
    description: 'Compact thermal blanket for emergency use',
    specification: '130*210 cm, 0.2kg, silver/gold reflective',
    quantity: 1,
    unit: 'piece',
    size: '130*210',
    weight: '0.2',
    dimensions: '130*210 cm',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/thermal-blanket-emergency.jpg',
    itemCode: 'BLK-004',
    categoryId: 'blankets-bedding',
  },
  {
    name: 'Cotton Blanket (Medium)',
    description: 'Medium weight cotton blanket for general use',
    specification: '220*240 cm, 1.5kg, 100% cotton',
    quantity: 1,
    unit: 'piece',
    size: '220*240',
    weight: '1.5',
    dimensions: '220*240 cm',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/cotton-blanket.jpg',
    itemCode: 'BLK-005',
    categoryId: 'blankets-bedding',
  },
  {
    name: 'Baby Blanket Set',
    description: 'Soft baby blanket set for infants',
    specification: '100*120 cm, 0.4kg, hypoallergenic material',
    quantity: 1,
    unit: 'set',
    size: '100*120',
    weight: '0.4',
    dimensions: '100*120 cm',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/baby-blanket.jpg',
    itemCode: 'BLK-006',
    categoryId: 'blankets-bedding',
  },
  {
    name: 'Waterproof Blanket',
    description: 'Waterproof blanket for outdoor use',
    specification: '200*180 cm, 1.2kg, waterproof coating',
    quantity: 1,
    unit: 'piece',
    size: '200*180',
    weight: '1.2',
    dimensions: '200*180 cm',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/waterproof-blanket.jpg',
    itemCode: 'BLK-007',
    categoryId: 'blankets-bedding',
  },
  {
    name: 'Fire Retardant Blanket',
    description: 'Fire retardant blanket for safety',
    specification: '180*200 cm, 2.1kg, fire retardant treated',
    quantity: 1,
    unit: 'piece',
    size: '180*200',
    weight: '2.1',
    dimensions: '180*200 cm',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/fire-retardant-blanket.jpg',
    itemCode: 'BLK-008',
    categoryId: 'blankets-bedding',
  },
  {
    name: 'Pillow (Standard)',
    description: 'Standard pillow for sleeping comfort',
    specification: '50*70 cm, 0.8kg, polyester filling',
    quantity: 1,
    unit: 'piece',
    size: '50*70',
    weight: '0.8',
    dimensions: '50*70 cm',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/pillow-standard.jpg',
    itemCode: 'BLK-009',
    categoryId: 'blankets-bedding',
  },
  {
    name: 'Pillow (Travel)',
    description: 'Compact travel pillow for portability',
    specification: '30*40 cm, 0.3kg, memory foam',
    quantity: 1,
    unit: 'piece',
    size: '30*40',
    weight: '0.3',
    dimensions: '30*40 cm',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/pillow-travel.jpg',
    itemCode: 'BLK-010',
    categoryId: 'blankets-bedding',
  },
  {
    name: 'Bed Sheet Set',
    description: 'Complete bed sheet set for single bed',
    specification: 'Fitted sheet, flat sheet, pillowcase, cotton blend',
    quantity: 1,
    unit: 'set',
    productType: 'kit',
    isKit: true,
    kitContents: [
      { item: 'Fitted Sheet', quantity: 1, size: '90*200 cm' },
      { item: 'Flat Sheet', quantity: 1, size: '180*200 cm' },
      { item: 'Pillowcase', quantity: 1, size: '50*70 cm' },
    ],
    referencePicture: '/images/bed-sheet-set.jpg',
    itemCode: 'BLK-011',
    categoryId: 'blankets-bedding',
  },
  {
    name: 'Towel Set',
    description: 'Bath towel set for personal hygiene',
    specification: 'Bath towel, hand towel, face towel, cotton',
    quantity: 1,
    unit: 'set',
    productType: 'kit',
    isKit: true,
    kitContents: [
      { item: 'Bath Towel', quantity: 1, size: '70*140 cm' },
      { item: 'Hand Towel', quantity: 1, size: '30*50 cm' },
      { item: 'Face Towel', quantity: 1, size: '25*25 cm' },
    ],
    referencePicture: '/images/towel-set.jpg',
    itemCode: 'BLK-012',
    categoryId: 'blankets-bedding',
  },
  {
    name: 'Mattress (Foam)',
    description: 'Foam mattress for sleeping comfort',
    specification: '90*200 cm, 5kg, high-density foam',
    quantity: 1,
    unit: 'piece',
    size: '90*200',
    weight: '5.0',
    dimensions: '90*200*10 cm',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/mattress-foam.jpg',
    itemCode: 'BLK-013',
    categoryId: 'blankets-bedding',
  },
  {
    name: 'Mattress (Inflatable)',
    description: 'Inflatable mattress for temporary use',
    specification: '100*200 cm, 1.5kg, PVC material',
    quantity: 1,
    unit: 'piece',
    size: '100*200',
    weight: '1.5',
    dimensions: '100*200*15 cm',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/mattress-inflatable.jpg',
    itemCode: 'BLK-014',
    categoryId: 'blankets-bedding',
  },
  {
    name: 'Sleeping Bag (Summer)',
    description: 'Lightweight sleeping bag for summer use',
    specification: '220*80 cm, 1.2kg, synthetic filling',
    quantity: 1,
    unit: 'piece',
    size: '220*80',
    weight: '1.2',
    dimensions: '220*80 cm',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/sleeping-bag-summer.jpg',
    itemCode: 'BLK-015',
    categoryId: 'blankets-bedding',
  },
  {
    name: 'Mattress Topper',
    description: 'Soft foam mattress topper for extra comfort',
    specification: '90*200 cm, 2cm thick, 1.2kg',
    quantity: 1,
    unit: 'piece',
    size: '90*200',
    weight: '1.2',
    dimensions: '90*200*2 cm',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/mattress-topper.jpg',
    itemCode: 'BLK-016',
    categoryId: 'blankets-bedding',
  },
  {
    name: 'Quilted Comforter',
    description: 'Warm quilted comforter for cold nights',
    specification: '220*240 cm, 2.5kg, polyester fill',
    quantity: 1,
    unit: 'piece',
    size: '220*240',
    weight: '2.5',
    dimensions: '220*240 cm',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/quilted-comforter.jpg',
    itemCode: 'BLK-017',
    categoryId: 'blankets-bedding',
  },
  {
    name: 'Sleeping Pad',
    description: 'Insulated sleeping pad for outdoor use',
    specification: '60*180 cm, 0.7kg, foam',
    quantity: 1,
    unit: 'piece',
    size: '60*180',
    weight: '0.7',
    dimensions: '60*180 cm',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/sleeping-pad.jpg',
    itemCode: 'BLK-018',
    categoryId: 'blankets-bedding',
  },
  {
    name: 'Travel Blanket',
    description: 'Compact travel blanket for portability',
    specification: '120*150 cm, 0.5kg, fleece',
    quantity: 1,
    unit: 'piece',
    size: '120*150',
    weight: '0.5',
    dimensions: '120*150 cm',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/travel-blanket.jpg',
    itemCode: 'BLK-019',
    categoryId: 'blankets-bedding',
  },
  {
    name: 'Double Sleeping Bag',
    description: 'Sleeping bag for two people',
    specification: '140*200 cm, 2.2kg, synthetic fill',
    quantity: 1,
    unit: 'piece',
    size: '140*200',
    weight: '2.2',
    dimensions: '140*200 cm',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/double-sleeping-bag.jpg',
    itemCode: 'BLK-020',
    categoryId: 'blankets-bedding',
  },
  {
    name: 'Weighted Blanket',
    description: 'Weighted blanket for comfort and anxiety relief',
    specification: '150*200 cm, 5kg, glass beads filling',
    quantity: 1,
    unit: 'piece',
    size: '150*200',
    weight: '5.0',
    dimensions: '150*200 cm',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/weighted-blanket.jpg',
    itemCode: 'BLK-021',
    categoryId: 'blankets-bedding',
  },
  {
    name: 'Electric Blanket',
    description: 'Electric blanket with adjustable heat settings',
    specification: '180*200 cm, 2kg, electric heating',
    quantity: 1,
    unit: 'piece',
    size: '180*200',
    weight: '2.0',
    dimensions: '180*200 cm',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/electric-blanket.jpg',
    itemCode: 'BLK-022',
    categoryId: 'blankets-bedding',
  },
  {
    name: 'Mosquito Net (Bed Size)',
    description: 'Mosquito net for single bed',
    specification: '100*200*150 cm, 0.4kg, polyester mesh',
    quantity: 1,
    unit: 'piece',
    size: '100*200*150',
    weight: '0.4',
    dimensions: '100*200*150 cm',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/mosquito-net-bed.jpg',
    itemCode: 'BLK-023',
    categoryId: 'blankets-bedding',
  },
  {
    name: 'Mattress Protector',
    description: 'Waterproof mattress protector',
    specification: '90*200 cm, 0.6kg, waterproof fabric',
    quantity: 1,
    unit: 'piece',
    size: '90*200',
    weight: '0.6',
    dimensions: '90*200 cm',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/mattress-protector.jpg',
    itemCode: 'BLK-024',
    categoryId: 'blankets-bedding',
  },
  {
    name: 'Sleeping Bag Liner',
    description: 'Cotton liner for sleeping bags',
    specification: '80*200 cm, 0.3kg, cotton',
    quantity: 1,
    unit: 'piece',
    size: '80*200',
    weight: '0.3',
    dimensions: '80*200 cm',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/sleeping-bag-liner.jpg',
    itemCode: 'BLK-025',
    categoryId: 'blankets-bedding',
  },
];

// Sample Products - Winterization Kits
const sampleWinterizationProducts = [
  {
    name: 'Men Winterization Kit',
    description: 'Complete winter clothing kit for adult men',
    specification: 'Includes jacket, gloves, hat, scarf, socks, and bag',
    quantity: 1,
    unit: 'kit',
    productType: 'kit',
    isKit: true,
    kitContents: [
      { item: 'Men Winter Jacket (Adult)', quantity: 1, size: 'L,XL' },
      { item: 'Winter Gloves, Hat and Scarf Set (Adult)', quantity: 1, size: 'M,L' },
      { item: 'Winter Socks Men (Adult)', quantity: 1, size: 'Adult Size' },
      { item: 'Bag with Logo Printed', quantity: 1, size: '55*25*25 cm, 400 grams' },
    ],
    dimensions: '55*25*25 cm',
    weight: '0.4',
    referencePicture: '/images/men-winter-kit.jpg',
    itemCode: 'WWK-MEN-001',
    categoryId: 'winterization-kits',
  },
  {
    name: 'Women Winterization Kit',
    description: 'Complete winter clothing kit for adult women',
    specification: 'Includes jacket, gloves, hat, scarf, socks, and bag',
    quantity: 1,
    unit: 'kit',
    productType: 'kit',
    isKit: true,
    kitContents: [
      { item: 'Woman Winter Jacket (Adult)', quantity: 1, size: 'M,L' },
      { item: 'Winter Gloves, Hat and Scarf Set (Adult)', quantity: 1, size: 'M,L' },
      { item: 'Winter Socks Woman (Adult)', quantity: 1, size: 'Adult Size' },
      { item: 'Bag with Logo Printed', quantity: 1, size: '55*25*25 cm, 400 grams' },
    ],
    dimensions: '55*25*25 cm',
    weight: '0.4',
    referencePicture: '/images/women-winter-kit.jpg',
    itemCode: 'WWK-WOMEN-001',
    categoryId: 'winterization-kits',
  },
  {
    name: 'Kids (Boy) Winterization Kit',
    description: 'Complete winter clothing kit for boys aged 8-12',
    specification: 'Includes jacket, gloves, hat, scarf, socks, and bag',
    quantity: 1,
    unit: 'kit',
    productType: 'kit',
    isKit: true,
    kitContents: [
      { item: 'Winter Jacket (Kids Size)', quantity: 1, size: 'Age between 8-12' },
      { item: 'Winter Gloves, Hat and Scarf Set (Kids Size)', quantity: 1, size: 'Age between 8-12' },
      { item: 'Winter Socks (Kids Size)', quantity: 1, size: 'Age between 8-12' },
      { item: 'Bag with Logo Printed', quantity: 1, size: '55*25*25 cm, 400 grams' },
    ],
    dimensions: '55*25*25 cm',
    weight: '0.4',
    referencePicture: '/images/kids-boy-winter-kit.jpg',
    itemCode: 'WWK-KIDS-BOY-001',
    categoryId: 'winterization-kits',
  },
  {
    name: 'Kids (Girl) Winterization Kit',
    description: 'Complete winter clothing kit for girls aged 8-12',
    specification: 'Includes jacket, gloves, hat, scarf, socks, and bag',
    quantity: 1,
    unit: 'kit',
    productType: 'kit',
    isKit: true,
    kitContents: [
      { item: 'Winter Jacket (Kids Size)', quantity: 1, size: 'Age between 8-12' },
      { item: 'Winter Gloves, Hat and Scarf Set (Kids Size)', quantity: 1, size: 'Age between 8-12' },
      { item: 'Socks (Kids Size)', quantity: 1, size: 'Age between 8-12' },
      { item: 'Bag with Logo Printed', quantity: 1, size: '55*25*25 cm, 400 grams' },
    ],
    dimensions: '55*25*25 cm',
    weight: '0.4',
    referencePicture: '/images/kids-girl-winter-kit.jpg',
    itemCode: 'WWK-KIDS-GIRL-001',
    categoryId: 'winterization-kits',
  },
  {
    name: 'Winter Jacket (Men - Large)',
    description: 'Heavy winter jacket for adult men',
    specification: 'Waterproof, insulated, size L, 1.2kg',
    quantity: 1,
    unit: 'piece',
    size: 'L',
    weight: '1.2',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/winter-jacket-men.jpg',
    itemCode: 'WWK-MEN-002',
    categoryId: 'winterization-kits',
  },
  {
    name: 'Winter Jacket (Men - XL)',
    description: 'Heavy winter jacket for adult men',
    specification: 'Waterproof, insulated, size XL, 1.3kg',
    quantity: 1,
    unit: 'piece',
    size: 'XL',
    weight: '1.3',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/winter-jacket-men-xl.jpg',
    itemCode: 'WWK-MEN-003',
    categoryId: 'winterization-kits',
  },
  {
    name: 'Winter Jacket (Women - Medium)',
    description: 'Heavy winter jacket for adult women',
    specification: 'Waterproof, insulated, size M, 1.1kg',
    quantity: 1,
    unit: 'piece',
    size: 'M',
    weight: '1.1',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/winter-jacket-women.jpg',
    itemCode: 'WWK-WOMEN-002',
    categoryId: 'winterization-kits',
  },
  {
    name: 'Winter Jacket (Women - Large)',
    description: 'Heavy winter jacket for adult women',
    specification: 'Waterproof, insulated, size L, 1.2kg',
    quantity: 1,
    unit: 'piece',
    size: 'L',
    weight: '1.2',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/winter-jacket-women-l.jpg',
    itemCode: 'WWK-WOMEN-003',
    categoryId: 'winterization-kits',
  },
  {
    name: 'Winter Jacket (Kids - Age 8-12)',
    description: 'Winter jacket for children aged 8-12',
    specification: 'Waterproof, insulated, kids size, 0.8kg',
    quantity: 1,
    unit: 'piece',
    size: '8-12',
    weight: '0.8',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/winter-jacket-kids.jpg',
    itemCode: 'WWK-KIDS-002',
    categoryId: 'winterization-kits',
  },
  {
    name: 'Winter Gloves (Adult)',
    description: 'Warm winter gloves for adults',
    specification: 'Insulated, waterproof, size M/L, 0.2kg',
    quantity: 1,
    unit: 'pair',
    size: 'M/L',
    weight: '0.2',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/winter-gloves-adult.jpg',
    itemCode: 'WWK-GLOVES-001',
    categoryId: 'winterization-kits',
  },
  {
    name: 'Winter Gloves (Kids)',
    description: 'Warm winter gloves for children',
    specification: 'Insulated, waterproof, kids size, 0.15kg',
    quantity: 1,
    unit: 'pair',
    size: 'Kids',
    weight: '0.15',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/winter-gloves-kids.jpg',
    itemCode: 'WWK-GLOVES-002',
    categoryId: 'winterization-kits',
  },
  {
    name: 'Winter Hat (Adult)',
    description: 'Warm winter hat for adults',
    specification: 'Wool blend, one size fits most, 0.1kg',
    quantity: 1,
    unit: 'piece',
    size: 'One Size',
    weight: '0.1',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/winter-hat-adult.jpg',
    itemCode: 'WWK-HAT-001',
    categoryId: 'winterization-kits',
  },
  {
    name: 'Winter Hat (Kids)',
    description: 'Warm winter hat for children',
    specification: 'Wool blend, kids size, 0.08kg',
    quantity: 1,
    unit: 'piece',
    size: 'Kids',
    weight: '0.08',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/winter-hat-kids.jpg',
    itemCode: 'WWK-HAT-002',
    categoryId: 'winterization-kits',
  },
  {
    name: 'Winter Scarf (Adult)',
    description: 'Warm winter scarf for adults',
    specification: 'Wool blend, 150cm length, 0.15kg',
    quantity: 1,
    unit: 'piece',
    size: '150cm',
    weight: '0.15',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/winter-scarf-adult.jpg',
    itemCode: 'WWK-SCARF-001',
    categoryId: 'winterization-kits',
  },
  {
    name: 'Winter Scarf (Kids)',
    description: 'Warm winter scarf for children',
    specification: 'Wool blend, 100cm length, 0.1kg',
    quantity: 1,
    unit: 'piece',
    size: '100cm',
    weight: '0.1',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/winter-scarf-kids.jpg',
    itemCode: 'WWK-SCARF-002',
    categoryId: 'winterization-kits',
  },
  {
    name: 'Winter Socks (Men)',
    description: 'Warm winter socks for men',
    specification: 'Wool blend, adult size, 0.1kg per pair',
    quantity: 1,
    unit: 'pair',
    size: 'Adult',
    weight: '0.1',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/winter-socks-men.jpg',
    itemCode: 'WWK-SOCKS-001',
    categoryId: 'winterization-kits',
  },
  {
    name: 'Winter Socks (Women)',
    description: 'Warm winter socks for women',
    specification: 'Wool blend, adult size, 0.08kg per pair',
    quantity: 1,
    unit: 'pair',
    size: 'Adult',
    weight: '0.08',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/winter-socks-women.jpg',
    itemCode: 'WWK-SOCKS-002',
    categoryId: 'winterization-kits',
  },
  {
    name: 'Winter Socks (Kids)',
    description: 'Warm winter socks for children',
    specification: 'Wool blend, kids size, 0.06kg per pair',
    quantity: 1,
    unit: 'pair',
    size: 'Kids',
    weight: '0.06',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/winter-socks-kids.jpg',
    itemCode: 'WWK-SOCKS-003',
    categoryId: 'winterization-kits',
  },
  {
    name: 'Thermal Underwear Set (Men)',
    description: 'Thermal underwear set for men',
    specification: 'Long johns and top, size L, 0.4kg',
    quantity: 1,
    unit: 'set',
    size: 'L',
    weight: '0.4',
    productType: 'kit',
    isKit: true,
    kitContents: [
      { item: 'Thermal Top', quantity: 1, size: 'L' },
      { item: 'Thermal Pants', quantity: 1, size: 'L' },
    ],
    referencePicture: '/images/thermal-underwear-men.jpg',
    itemCode: 'WWK-THERMAL-001',
    categoryId: 'winterization-kits',
  },
  {
    name: 'Thermal Underwear Set (Women)',
    description: 'Thermal underwear set for women',
    specification: 'Long johns and top, size M, 0.35kg',
    quantity: 1,
    unit: 'set',
    size: 'M',
    weight: '0.35',
    productType: 'kit',
    isKit: true,
    kitContents: [
      { item: 'Thermal Top', quantity: 1, size: 'M' },
      { item: 'Thermal Pants', quantity: 1, size: 'M' },
    ],
    referencePicture: '/images/thermal-underwear-women.jpg',
    itemCode: 'WWK-THERMAL-002',
    categoryId: 'winterization-kits',
  },
  {
    name: 'Thermal Underwear Set (Kids)',
    description: 'Thermal underwear set for children',
    specification: 'Long johns and top, kids size, 0.25kg',
    quantity: 1,
    unit: 'set',
    size: 'Kids',
    weight: '0.25',
    productType: 'kit',
    isKit: true,
    kitContents: [
      { item: 'Thermal Top', quantity: 1, size: 'Kids' },
      { item: 'Thermal Pants', quantity: 1, size: 'Kids' },
    ],
    referencePicture: '/images/thermal-underwear-kids.jpg',
    itemCode: 'WWK-THERMAL-003',
    categoryId: 'winterization-kits',
  },
  {
    name: 'Winter Boots (Men)',
    description: 'Waterproof winter boots for men',
    specification: 'Insulated, waterproof, size 42-44, 1.5kg',
    quantity: 1,
    unit: 'pair',
    size: '42-44',
    weight: '1.5',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/winter-boots-men.jpg',
    itemCode: 'WWK-BOOTS-001',
    categoryId: 'winterization-kits',
  },
  {
    name: 'Winter Boots (Women)',
    description: 'Waterproof winter boots for women',
    specification: 'Insulated, waterproof, size 38-40, 1.3kg',
    quantity: 1,
    unit: 'pair',
    size: '38-40',
    weight: '1.3',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/winter-boots-women.jpg',
    itemCode: 'WWK-BOOTS-002',
    categoryId: 'winterization-kits',
  },
  {
    name: 'Winter Boots (Kids)',
    description: 'Waterproof winter boots for children',
    specification: 'Insulated, waterproof, kids size, 0.8kg',
    quantity: 1,
    unit: 'pair',
    size: 'Kids',
    weight: '0.8',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/winter-boots-kids.jpg',
    itemCode: 'WWK-BOOTS-003',
    categoryId: 'winterization-kits',
  },
];

// Sample Products - Kitchen Sets
const sampleKitchenProducts = [
  {
    name: 'Kitchen Set - UNHCR (Type B - SS)',
    description: 'Complete kitchen set with stainless steel cookware',
    specification: 'Includes cooking pots, pans, bowls, plates, cups, and utensils',
    quantity: 1,
    unit: 'set',
    productType: 'kit',
    isKit: true,
    kitContents: [
      { item: 'Cooking Pot 7L', quantity: 1, specification: '7 Ltr' },
      { item: 'Frying Pan 2.5L (used as Lid for Cooking Pot 7L)', quantity: 1, specification: '2.5 Ltr' },
      { item: 'Cooking Pot 5L with Lid', quantity: 1, specification: '5 Ltr' },
      { item: 'Bowl 1L', quantity: 5, specification: '1 Ltr' },
      { item: 'Plates 0.75L', quantity: 5, specification: '0.75 Ltr' },
      { item: 'Cups 0.3L', quantity: 5, specification: '0.3 Ltr' },
      { item: 'Table Spoon 10ML', quantity: 5, specification: '10 ML' },
      { item: 'Table Fork 17cm', quantity: 5, specification: '17 Cm' },
      { item: 'Table Knife 17cm', quantity: 5, specification: '17 Cm' },
      { item: 'Kitchen Knife 15cm', quantity: 1, specification: '15 cm' },
      { item: 'Spoon Wooden Stirring 30cm', quantity: 1, specification: '20 cm' },
      { item: 'Serving Spoon 30cm', quantity: 2, specification: '30 cm' },
      { item: 'Scoring Pad', quantity: 2, specification: '' },
    ],
    referencePicture: '/images/kitchen-set-unhcr.jpg',
    itemCode: 'KIT-UNHCR-001',
    categoryId: 'kitchen-sets',
  },
  {
    name: 'Cooking Pot (7L)',
    description: 'Large cooking pot for family meals',
    specification: 'Stainless steel, 7 liter capacity, 1.8kg',
    quantity: 1,
    unit: 'piece',
    volume: '7',
    weight: '1.8',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/cooking-pot-7l.jpg',
    itemCode: 'KIT-POT-001',
    categoryId: 'kitchen-sets',
  },
  {
    name: 'Cooking Pot (5L)',
    description: 'Medium cooking pot with lid',
    specification: 'Stainless steel, 5 liter capacity, 1.5kg',
    quantity: 1,
    unit: 'piece',
    volume: '5',
    weight: '1.5',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/cooking-pot-5l.jpg',
    itemCode: 'KIT-POT-002',
    categoryId: 'kitchen-sets',
  },
  {
    name: 'Cooking Pot (3L)',
    description: 'Small cooking pot for small meals',
    specification: 'Stainless steel, 3 liter capacity, 1.0kg',
    quantity: 1,
    unit: 'piece',
    volume: '3',
    weight: '1.0',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/cooking-pot-3l.jpg',
    itemCode: 'KIT-POT-003',
    categoryId: 'kitchen-sets',
  },
  {
    name: 'Frying Pan (2.5L)',
    description: 'Frying pan with handle',
    specification: 'Stainless steel, 2.5 liter capacity, 0.8kg',
    quantity: 1,
    unit: 'piece',
    volume: '2.5',
    weight: '0.8',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/frying-pan.jpg',
    itemCode: 'KIT-PAN-001',
    categoryId: 'kitchen-sets',
  },
  {
    name: 'Bowl Set (1L)',
    description: 'Set of 5 bowls for serving',
    specification: 'Stainless steel, 1 liter each, 0.3kg each',
    quantity: 5,
    unit: 'pieces',
    volume: '1',
    weight: '0.3',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/bowl-set.jpg',
    itemCode: 'KIT-BOWL-001',
    categoryId: 'kitchen-sets',
  },
  {
    name: 'Plate Set (0.75L)',
    description: 'Set of 5 plates for serving',
    specification: 'Stainless steel, 0.75 liter each, 0.2kg each',
    quantity: 5,
    unit: 'pieces',
    volume: '0.75',
    weight: '0.2',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/plate-set.jpg',
    itemCode: 'KIT-PLATE-001',
    categoryId: 'kitchen-sets',
  },
  {
    name: 'Cup Set (0.3L)',
    description: 'Set of 5 cups for drinking',
    specification: 'Stainless steel, 0.3 liter each, 0.15kg each',
    quantity: 5,
    unit: 'pieces',
    volume: '0.3',
    weight: '0.15',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/cup-set.jpg',
    itemCode: 'KIT-CUP-001',
    categoryId: 'kitchen-sets',
  },
  {
    name: 'Table Spoon Set',
    description: 'Set of 5 table spoons',
    specification: 'Stainless steel, 10ml capacity each',
    quantity: 5,
    unit: 'pieces',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/table-spoon-set.jpg',
    itemCode: 'KIT-SPOON-001',
    categoryId: 'kitchen-sets',
  },
  {
    name: 'Table Fork Set',
    description: 'Set of 5 table forks',
    specification: 'Stainless steel, 17cm length each',
    quantity: 5,
    unit: 'pieces',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/table-fork-set.jpg',
    itemCode: 'KIT-FORK-001',
    categoryId: 'kitchen-sets',
  },
  {
    name: 'Table Knife Set',
    description: 'Set of 5 table knives',
    specification: 'Stainless steel, 17cm length each',
    quantity: 5,
    unit: 'pieces',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/table-knife-set.jpg',
    itemCode: 'KIT-KNIFE-001',
    categoryId: 'kitchen-sets',
  },
  {
    name: 'Kitchen Knife',
    description: 'Kitchen knife for food preparation',
    specification: 'Stainless steel, 15cm blade, 0.2kg',
    quantity: 1,
    unit: 'piece',
    weight: '0.2',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/kitchen-knife.jpg',
    itemCode: 'KIT-KNIFE-002',
    categoryId: 'kitchen-sets',
  },
  {
    name: 'Wooden Stirring Spoon',
    description: 'Wooden spoon for stirring',
    specification: 'Wood, 30cm length, 0.1kg',
    quantity: 1,
    unit: 'piece',
    weight: '0.1',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/wooden-spoon.jpg',
    itemCode: 'KIT-SPOON-002',
    categoryId: 'kitchen-sets',
  },
  {
    name: 'Serving Spoon Set',
    description: 'Set of 2 serving spoons',
    specification: 'Stainless steel, 30cm length each',
    quantity: 2,
    unit: 'pieces',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/serving-spoon-set.jpg',
    itemCode: 'KIT-SPOON-003',
    categoryId: 'kitchen-sets',
  },
  {
    name: 'Cutting Board',
    description: 'Plastic cutting board for food preparation',
    specification: 'Plastic, 30*20 cm, 0.3kg',
    quantity: 1,
    unit: 'piece',
    dimensions: '30*20 cm',
    weight: '0.3',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/cutting-board.jpg',
    itemCode: 'KIT-BOARD-001',
    categoryId: 'kitchen-sets',
  },
  {
    name: 'Can Opener',
    description: 'Manual can opener',
    specification: 'Stainless steel, manual operation, 0.1kg',
    quantity: 1,
    unit: 'piece',
    weight: '0.1',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/can-opener.jpg',
    itemCode: 'KIT-OPENER-001',
    categoryId: 'kitchen-sets',
  },
  {
    name: 'Lighter',
    description: 'Disposable lighter for cooking',
    specification: 'Plastic, disposable, 0.05kg',
    quantity: 1,
    unit: 'piece',
    weight: '0.05',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/lighter.jpg',
    itemCode: 'KIT-LIGHTER-001',
    categoryId: 'kitchen-sets',
  },
  {
    name: 'Matches',
    description: 'Safety matches for cooking',
    specification: 'Wooden matches, 50 per box, 0.02kg',
    quantity: 1,
    unit: 'box',
    weight: '0.02',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/matches.jpg',
    itemCode: 'KIT-MATCHES-001',
    categoryId: 'kitchen-sets',
  },
  {
    name: 'Kitchen Towel Set',
    description: 'Set of 2 kitchen towels',
    specification: 'Cotton, 40*60 cm each, 0.1kg each',
    quantity: 2,
    unit: 'pieces',
    dimensions: '40*60 cm',
    weight: '0.1',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/kitchen-towel-set.jpg',
    itemCode: 'KIT-TOWEL-001',
    categoryId: 'kitchen-sets',
  },
  {
    name: 'Dish Soap',
    description: 'Liquid dish soap for cleaning',
    specification: '500ml bottle, biodegradable, 0.5kg',
    quantity: 1,
    unit: 'bottle',
    volume: '0.5',
    weight: '0.5',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/dish-soap.jpg',
    itemCode: 'KIT-SOAP-001',
    categoryId: 'kitchen-sets',
  },
  {
    name: 'Sponge Set',
    description: 'Set of 3 cleaning sponges',
    specification: 'Cellulose sponges, 3 pieces, 0.1kg',
    quantity: 3,
    unit: 'pieces',
    weight: '0.1',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/sponge-set.jpg',
    itemCode: 'KIT-SPONGE-001',
    categoryId: 'kitchen-sets',
  },
  {
    name: 'Food Storage Container Set',
    description: 'Set of 3 food storage containers',
    specification: 'Plastic, 1L, 2L, 3L capacities, 0.5kg total',
    quantity: 3,
    unit: 'pieces',
    weight: '0.5',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/storage-containers.jpg',
    itemCode: 'KIT-CONTAINER-001',
    categoryId: 'kitchen-sets',
  },
  {
    name: 'Tea Kettle',
    description: 'Stainless steel tea kettle',
    specification: 'Stainless steel, 2L capacity, 0.8kg',
    quantity: 1,
    unit: 'piece',
    volume: '2',
    weight: '0.8',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/tea-kettle.jpg',
    itemCode: 'KIT-KETTLE-001',
    categoryId: 'kitchen-sets',
  },
  {
    name: 'Coffee Pot',
    description: 'Stainless steel coffee pot',
    specification: 'Stainless steel, 1L capacity, 0.6kg',
    quantity: 1,
    unit: 'piece',
    volume: '1',
    weight: '0.6',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/coffee-pot.jpg',
    itemCode: 'KIT-COFFEE-001',
    categoryId: 'kitchen-sets',
  },
  {
    name: 'Salt and Pepper Shakers',
    description: 'Set of salt and pepper shakers',
    specification: 'Plastic, 100g each, 0.2kg total',
    quantity: 2,
    unit: 'pieces',
    weight: '0.2',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/salt-pepper.jpg',
    itemCode: 'KIT-SEASONING-001',
    categoryId: 'kitchen-sets',
  },
  {
    name: 'Cooking Oil (1L)',
    description: 'Vegetable cooking oil',
    specification: '1 liter bottle, vegetable oil, 0.9kg',
    quantity: 1,
    unit: 'bottle',
    volume: '1',
    weight: '0.9',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/cooking-oil.jpg',
    itemCode: 'KIT-OIL-001',
    categoryId: 'kitchen-sets',
  },
  {
    name: 'Sugar (1kg)',
    description: 'Granulated sugar',
    specification: '1 kilogram bag, granulated sugar, 1kg',
    quantity: 1,
    unit: 'bag',
    weight: '1.0',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/sugar.jpg',
    itemCode: 'KIT-SUGAR-001',
    categoryId: 'kitchen-sets',
  },
  {
    name: 'Tea Bags (50 count)',
    description: 'Black tea bags',
    specification: '50 tea bags, black tea, 0.1kg',
    quantity: 50,
    unit: 'bags',
    weight: '0.1',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/tea-bags.jpg',
    itemCode: 'KIT-TEA-001',
    categoryId: 'kitchen-sets',
  },
  {
    name: 'Coffee (250g)',
    description: 'Ground coffee',
    specification: '250 gram bag, ground coffee, 0.25kg',
    quantity: 1,
    unit: 'bag',
    weight: '0.25',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/coffee-ground.jpg',
    itemCode: 'KIT-COFFEE-002',
    categoryId: 'kitchen-sets',
  },
];

// Sample Products - First Aid
const sampleFirstAidProducts = [
  {
    name: 'First Aid Kit (Basic)',
    description: 'Basic first aid kit for minor injuries',
    specification: 'Bandages, antiseptic wipes, gauze, tape, scissors',
    quantity: 1,
    unit: 'kit',
    productType: 'kit',
    isKit: true,
    kitContents: [
      { item: 'Bandages', quantity: 10 },
      { item: 'Antiseptic Wipes', quantity: 5 },
      { item: 'Gauze Pads', quantity: 5 },
      { item: 'Medical Tape', quantity: 1 },
      { item: 'Scissors', quantity: 1 },
    ],
    referencePicture: '/images/first-aid-basic.jpg',
    itemCode: 'FAK-001',
    categoryId: 'first-aid',
  },
  {
    name: 'First Aid Kit (Comprehensive)',
    description: 'Comprehensive first aid kit for emergencies',
    specification: 'Includes splints, gloves, CPR mask, and more',
    quantity: 1,
    unit: 'kit',
    productType: 'kit',
    isKit: true,
    kitContents: [
      { item: 'Splints', quantity: 2 },
      { item: 'Gloves', quantity: 4 },
      { item: 'CPR Mask', quantity: 1 },
      { item: 'Bandages', quantity: 20 },
      { item: 'Antiseptic Wipes', quantity: 10 },
    ],
    referencePicture: '/images/first-aid-comprehensive.jpg',
    itemCode: 'FAK-002',
    categoryId: 'first-aid',
  },
  {
    name: 'Burn Care Kit',
    description: 'Specialized kit for treating burns',
    specification: 'Burn dressings, gel, bandages, gloves',
    quantity: 1,
    unit: 'kit',
    productType: 'kit',
    isKit: true,
    kitContents: [
      { item: 'Burn Dressings', quantity: 3 },
      { item: 'Burn Gel', quantity: 2 },
      { item: 'Bandages', quantity: 5 },
      { item: 'Gloves', quantity: 2 },
    ],
    referencePicture: '/images/burn-care-kit.jpg',
    itemCode: 'FAK-003',
    categoryId: 'first-aid',
  },
  {
    name: 'Eye Wash Kit',
    description: 'Kit for emergency eye washing',
    specification: 'Eye wash solution, eye pads, instructions',
    quantity: 1,
    unit: 'kit',
    productType: 'kit',
    isKit: true,
    kitContents: [
      { item: 'Eye Wash Solution', quantity: 2 },
      { item: 'Eye Pads', quantity: 4 },
      { item: 'Instructions', quantity: 1 },
    ],
    referencePicture: '/images/eye-wash-kit.jpg',
    itemCode: 'FAK-004',
    categoryId: 'first-aid',
  },
  {
    name: 'CPR Mask',
    description: 'CPR mask for resuscitation',
    specification: 'One-way valve, compact case',
    quantity: 1,
    unit: 'piece',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/cpr-mask.jpg',
    itemCode: 'FAK-005',
    categoryId: 'first-aid',
  },
  {
    name: 'Trauma Shears',
    description: 'Heavy-duty shears for cutting clothing and bandages',
    specification: 'Stainless steel, 18cm',
    quantity: 1,
    unit: 'piece',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/trauma-shears.jpg',
    itemCode: 'FAK-006',
    categoryId: 'first-aid',
  },
  {
    name: 'Instant Cold Pack',
    description: 'Single-use cold pack for injuries',
    specification: '100g, squeezable',
    quantity: 1,
    unit: 'piece',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/cold-pack.jpg',
    itemCode: 'FAK-007',
    categoryId: 'first-aid',
  },
  {
    name: 'Elastic Bandage',
    description: 'Elastic bandage for sprains and strains',
    specification: '5cm x 4.5m',
    quantity: 1,
    unit: 'piece',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/elastic-bandage.jpg',
    itemCode: 'FAK-008',
    categoryId: 'first-aid',
  },
  {
    name: 'Digital Thermometer',
    description: 'Digital thermometer for temperature measurement',
    specification: 'Battery operated, LCD display',
    quantity: 1,
    unit: 'piece',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/thermometer.jpg',
    itemCode: 'FAK-009',
    categoryId: 'first-aid',
  },
  {
    name: 'Medical Gloves (Latex-Free)',
    description: 'Latex-free medical gloves',
    specification: 'Box of 10 pairs',
    quantity: 10,
    unit: 'pairs',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/medical-gloves.jpg',
    itemCode: 'FAK-010',
    categoryId: 'first-aid',
  },
];

// Sample Products - Water & Sanitation
const sampleWaterProducts = [
  {
    name: 'Plastic Water Bucket (With Tap)',
    description: '14L plastic water bucket with tap',
    specification: 'HDPE, tight-fitting lid, spigot, white',
    quantity: 1,
    unit: 'piece',
    volume: '14',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/water-bucket-tap.jpg',
    itemCode: 'WAT-001',
    categoryId: 'water-sanitation',
  },
  {
    name: 'Plastic Water Bucket (No Tap)',
    description: '14L plastic water bucket without tap',
    specification: 'HDPE, tight-fitting lid, white',
    quantity: 1,
    unit: 'piece',
    volume: '14',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/water-bucket.jpg',
    itemCode: 'WAT-002',
    categoryId: 'water-sanitation',
  },
  {
    name: 'Jerry Can (10L)',
    description: '10L collapsible jerry can',
    specification: 'LDPE, food grade, 0.17kg',
    quantity: 1,
    unit: 'piece',
    volume: '10',
    weight: '0.17',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/jerry-can-10l.jpg',
    itemCode: 'WAT-003',
    categoryId: 'water-sanitation',
  },
  {
    name: 'Jerry Can (20L)',
    description: '20L collapsible jerry can',
    specification: 'LDPE, food grade, 0.27kg',
    quantity: 1,
    unit: 'piece',
    volume: '20',
    weight: '0.27',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/jerry-can-20l.jpg',
    itemCode: 'WAT-004',
    categoryId: 'water-sanitation',
  },
  {
    name: 'Stainless Steel Water Filter',
    description: '24L SS water filter with 2-stage filtration',
    specification: '2 buckets, 2.33kg',
    quantity: 1,
    unit: 'set',
    volume: '24',
    weight: '2.33',
    productType: 'kit',
    isKit: true,
    kitContents: [
      { item: 'SS Bucket', quantity: 2 },
      { item: 'Filter Cartridge', quantity: 2 },
    ],
    referencePicture: '/images/ss-water-filter.jpg',
    itemCode: 'WAT-005',
    categoryId: 'water-sanitation',
  },
  {
    name: 'Bottle Filter',
    description: 'Portable water filtration bottle',
    specification: '600ml, Tritan, 2-stage filter',
    quantity: 1,
    unit: 'piece',
    volume: '0.6',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/bottle-filter.jpg',
    itemCode: 'WAT-006',
    categoryId: 'water-sanitation',
  },
  {
    name: 'Water Purification Tablets',
    description: 'Tablets for emergency water purification',
    specification: 'Bottle of 100 tablets',
    quantity: 1,
    unit: 'bottle',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/water-tablets.jpg',
    itemCode: 'WAT-007',
    categoryId: 'water-sanitation',
  },
  {
    name: 'Handwashing Station',
    description: 'Portable handwashing station',
    specification: '10L tank, tap, soap holder',
    quantity: 1,
    unit: 'set',
    productType: 'kit',
    isKit: true,
    kitContents: [
      { item: 'Tank', quantity: 1 },
      { item: 'Tap', quantity: 1 },
      { item: 'Soap Holder', quantity: 1 },
    ],
    referencePicture: '/images/handwashing-station.jpg',
    itemCode: 'WAT-008',
    categoryId: 'water-sanitation',
  },
  {
    name: 'Soap (Bar)',
    description: 'Bar soap for hygiene',
    specification: '100g, antibacterial',
    quantity: 1,
    unit: 'piece',
    productType: 'individual',
    isKit: false,
    referencePicture: '/images/soap-bar.jpg',
    itemCode: 'WAT-009',
    categoryId: 'water-sanitation',
  },
  {
    name: 'Toothbrush & Toothpaste Set',
    description: 'Set for oral hygiene',
    specification: '1 toothbrush, 1 toothpaste',
    quantity: 1,
    unit: 'set',
    productType: 'kit',
    isKit: true,
    kitContents: [
      { item: 'Toothbrush', quantity: 1 },
      { item: 'Toothpaste', quantity: 1 },
    ],
    referencePicture: '/images/toothbrush-toothpaste.jpg',
    itemCode: 'WAT-010',
    categoryId: 'water-sanitation',
  },
];

// Sample Products - Ready-to-Eat Food
const sampleFoodProducts = [
  {
    name: 'RTE Parcel',
    description: 'Ready-to-eat food parcel with various non-perishable items',
    specification: 'Complete food parcel with 9 different food items',
    quantity: 1,
    unit: 'parcel',
    productType: 'kit',
    isKit: true,
    kitContents: [
      { item: 'JAM 450 gr.', quantity: 2 },
      { item: 'LUNCHEON MEAT 340 gr', quantity: 4 },
      { item: 'TUNA 160 gr', quantity: 4 },
      { item: 'BAKED BEANS 420 gr', quantity: 4 },
      { item: 'CHICK PEAS 400 gr', quantity: 4 },
      { item: 'SARDINE 155 gr', quantity: 4 },
      { item: 'FOUL MEDAMMAS 400 gr', quantity: 4 },
      { item: 'HUMMUS THAHINA 380 gr', quantity: 4 },
      { item: 'HALAWA 900 gr', quantity: 2 },
    ],
    shelfLife: 365,
    storageConditions: 'Store in cool, dry place',
    referencePicture: '/images/rte-parcel.jpg',
    itemCode: 'RTE-001',
    categoryId: 'ready-to-eat-food',
  },
];

// Sample Products - Shelter & Tents
const sampleShelterProducts = [
  {
    name: 'Tents UNHCR Standards',
    description: 'Standard UNHCR tent for family shelter',
    specification: 'Area: 26 m2 (approx.), Size: 6.50 x 4.00 m, Material: Made of natural colour 320 g/m2 polyester / cotton, rot proof & water proof blend fabric, Weight: 55 Kgs (approx.), 0.16 cbm (approx.-1 Pc)',
    quantity: 1,
    unit: 'piece',
    productType: 'individual',
    isKit: false,
    weight: '55',
    dimensions: '6.50 x 4.00 m',
    referencePicture: '/images/tent-unhcr.jpg',
    itemCode: 'TENT-001',
    categoryId: 'shelter-tents',
  },
  {
    name: 'Thermal Fleece Blankets (Low, Medium and High) UNHCR Standard',
    description: 'Thermal fleece blankets in different thickness levels',
    specification: '150*200 Cm, 1.15 to 1.35 kg, 100% Polyester',
    quantity: 1,
    unit: 'piece',
    productType: 'individual',
    isKit: false,
    size: '150*200',
    weight: '1.25',
    dimensions: '150*200 cm',
    referencePicture: '/images/thermal-blanket.jpg',
    itemCode: 'TBL-001',
    categoryId: 'shelter-tents',
  },
  {
    name: 'Sleeping Mats UNHCR Standard',
    description: 'Waterproof sleeping mats for outdoor use',
    specification: '90*180 Cm/1.62 Sqm, Waterproof, tearproof and material trim finish, Suitable for one adult or two children, Will last for +12 months of use under hard tropical conditions',
    quantity: 1,
    unit: 'piece',
    productType: 'individual',
    isKit: false,
    size: '90*180',
    dimensions: '90*180 cm',
    referencePicture: '/images/sleeping-mat.jpg',
    itemCode: 'SM-001',
    categoryId: 'shelter-tents',
  },
  {
    name: 'Sleeping Bag',
    description: 'Square angle shape sleeping bag with 2 sides opening',
    specification: 'Sleeping bag, square angle shape, 2 sides opening, 0.7 x 1.9m, folded (= 1.4 x 1.9m open), Dark colour lining outside, and light colour inside – not white, 30mm for one layer (when open), 2 strong zips of each 1.9m and 0.7m, plastic.',
    quantity: 1,
    unit: 'piece',
    productType: 'individual',
    isKit: false,
    dimensions: '0.7 x 1.9m',
    referencePicture: '/images/sleeping-bag.jpg',
    itemCode: 'SB-001',
    categoryId: 'shelter-tents',
  },
  {
    name: 'Mosquito Net WHO Approved',
    description: 'WHO approved mosquito net for malaria prevention',
    specification: 'Fabric weight: 30 gram per square meter +10%, Enhanced durability: 21 + washes, Flammability test: Class 1 (16-CFR 1610CS191-53), Size: 190cm width x150cm height x180cm length, Material: 100% Polyester, Colour: White, Mesh Size: Minimum 130 holes per inch2',
    quantity: 1,
    unit: 'piece',
    productType: 'individual',
    isKit: false,
    dimensions: '190cm x 150cm x 180cm',
    referencePicture: '/images/mosquito-net.jpg',
    itemCode: 'MN-001',
    categoryId: 'shelter-tents',
  },
  {
    name: 'Tarpaulin UNHCR Standard',
    description: 'Fire retardant, waterproof tarpaulin for shelter protection',
    specification: 'Fire retardant (optional)*, waterproof, rotproof and UV-resistant, Reinforced plastic tarpaulin in 4m x 5m sheet or 4m x 50m roll developed by international research project and designed for long outdoor use in all climates, Highly recommended for family shelter protection, Made of woven high density black polyethylene (HDPE) fibers, warp x weft, laminated on both sides with low density polyethylene (LDPE) coating',
    quantity: 1,
    unit: 'piece',
    productType: 'individual',
    isKit: false,
    dimensions: '4m x 5m',
    referencePicture: '/images/tarpaulin.jpg',
    itemCode: 'TARP-001',
    categoryId: 'shelter-tents',
  },
];

// Helper function to get all sample products
function getAllSampleProducts() {
  return [
    ...sampleBlanketProducts,
    ...sampleWinterizationProducts,
    ...sampleKitchenProducts,
    ...sampleFirstAidProducts,
    ...sampleWaterProducts,
    ...sampleFoodProducts,
    ...sampleShelterProducts,
  ];
}

// Load environment variables
config({ path: '.env' });

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle(sql as any, { logger: false });

async function setupDatabase() {
  console.log('🚀 Setting up database...');

  try {
    // Check if categories already exist
    const existingCategories = await db
      .select()
      .from(productCategory)
      .where(eq(productCategory.isActive, true));
    
    if (existingCategories.length > 0) {
      console.log('✅ Product categories already exist, skipping...');
      return;
    }

    // Create product categories
    console.log('📦 Creating product categories...');
    const createdCategories = [];
    
    for (const category of sampleProductCategories) {
      const [createdCategory] = await db
        .insert(productCategory)
        .values(category)
        .returning();
      createdCategories.push(createdCategory);
      console.log(`✅ Created category: ${createdCategory.name}`);
    }

    // Create a mapping of category names to IDs
    const categoryMap = new Map(
      createdCategories.map((cat) => [cat.name, cat.id]),
    );

    // Get all sample products and assign category IDs
    const allProducts = getAllSampleProducts();
    
    console.log('📦 Creating products...');
    let productCount = 0;
    
    for (const productData of allProducts) {
      // Map placeholder category IDs to actual category names
      let categoryId = '';
      
      switch (productData.categoryId) {
        case 'blankets-bedding':
          categoryId = categoryMap.get('Blankets & Bedding') || '';
          break;
        case 'winterization-kits':
          categoryId = categoryMap.get('Winterization Kits') || '';
          break;
        case 'kitchen-sets':
          categoryId = categoryMap.get('Kitchen Sets') || '';
          break;
        case 'first-aid':
          categoryId = categoryMap.get('First Aid') || '';
          break;
        case 'water-sanitation':
          categoryId = categoryMap.get('Water & Sanitation') || '';
          break;
        case 'ready-to-eat-food':
          categoryId = categoryMap.get('Ready-to-Eat Food') || '';
          break;
        case 'shelter-tents':
          categoryId = categoryMap.get('Shelter & Tents') || '';
          break;
        default:
          console.warn(`⚠️  Unknown category ID: ${productData.categoryId} for product: ${productData.name}`);
          continue;
      }

      if (categoryId) {
        const productWithCategory = { ...productData, categoryId };
        await db.insert(product).values(productWithCategory);
        productCount++;
        console.log(`✅ Created product: ${productData.name}`);
      } else {
        console.warn(`⚠️  Could not find category for product: ${productData.name}`);
      }
    }

    console.log(
      `🎉 Database setup complete! Created ${createdCategories.length} categories and ${productCount} products.`,
    );
  } catch (error) {
    console.error('❌ Error setting up database:', error);
    process.exit(1);
  }
}

// Run the setup
setupDatabase()
  .then(() => {
    console.log('✅ Database setup completed successfully!');
    process.exit(0);
  })
  .catch((error) => {
    console.error('❌ Database setup failed:', error);
    process.exit(1);
  }); 